name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Rust Projects with Cross
        uses: houseabsolute/actions-rust-cross@v1.0.6
      - name: Release Rust Project Binaries as GitHub Releases
        uses: houseabsolute/actions-rust-release@v0.0.7
